#!/bin/sh

BLANK='#00000000'
CLEAR='#ffffff22'
DEFAULT='ffffffE6'
TEXT='#ffffffE6'
WRONG='#bf616aE6'
VERIFYING='#81a1c1E6'

i3lock \
  --insidever-color=$CLEAR \
  --ringver-color=$VERIFYING \
  \
  --insidewrong-color=$CLEAR \
  --ringwrong-color=$WRONG \
  \
  --inside-color=$BLANK \
  --ring-color=$DEFAULT \
  --line-color=$BLANK \
  --separator-color=$DEFAULT \
  \
  --verif-color=$TEXT \
  --wrong-color=$TEXT \
  --time-color=$TEXT \
  --date-color=$TEXT \
  --layout-color=$TEXT \
  --keyhl-color=$WRONG \
  --bshl-color=$WRONG \
  \
  --screen 1 \
  --blur 9 \
  --clock \
  --indicator \
  --time-str="%I:%M %p" \
  --date-str="%m/%d/%Y"
